language: python
cache: pip
env:
  global:
  - TRAVIS_TAG=0.1.$TRAVIS_BUILD_NUMBER
  - COMMIT_MESSAGE=release-version-v$TRAVIS_TAG"
  - GIT_REPO=pyndv
  - secure: uiZpdvEJy6MxfEoDcc/6RI6NMrwZt2Lx79FxS1hpcjbKoJ2wDtbRCj4W2SNj9X2OjmcqE2xyUli9eIXMQO8EW2fEhhecudV/Ev6YynqW5icA2nvvbXqpHT78YgkBUNLXTBL+xjvOQxlq/ZgIsXFC6usH7q50VT1LNW7/vZTRGWnBqsuftEDpwaMNihqwLz3Q1j1aRpK2VDNAA2Ul5F18fwsDooAx4xUJCOhGpQnYm7MujSzYk/6EfNaqVOu7Kv4etJjJAuIBx01i/U/1tvrdaZAT0lvsYz9t8rqvzawMvdwCBnusXEI9P+mWlcrax4aBixgyKo06pcFPodsM16c8Z0MWn8zBFnWlSVasWN5WKX6R+6zf5DGU2Gr0MQQ1uv0rUINy+1/gz10QJa0XWdBE4JTAbQ0RvQrFVVLtn7g8Mra5iDiTkp135pNEdFY+aC2T+rv7GdHc+mk/NE68SZgHeNGQysIJxFuaTc+rq/uV6TgNxH61ahk1Dc2UY1JYjUCR3ZkT8pqutZ2E9bjkJ4Cw46DQgXWXjioLSOvDhi9FOihYUUqnxx26M2+9KLt2wnsN9KZhgNGifZAtrSValYcglL8T57psu9vQVM0aStPu6ykrMH0shJluD8LeDmDtDmkqB/4ZFyumbT0IazFMoZKZu4Di2ayfVEM2JG5qcUKrF/U=
branches:
  only:
  - master
install: pip install -r requirements-ci.txt
before_script:
- make run-bumpversion buildnumber=$TRAVIS_TAG
script: make run-tox
before_deploy:
- git config --local user.name "$GIT_USER_NAME"
- git config --local user.email "$GIT_USER_EMAIL"
- git remote rm origin
- git remote add origin https://$GIT_USER_NAME:$GH_TOKEN@github.com/$GIT_USER_NAME/$GIT_REPO.git
- git push origin $TRAVIS_BRANCH --tags 2>&1
deploy:
- provider: pypi
  user: "$USER_PYPI"
  password: 
    secure: I61x45tFwjE6SffSiYqNiJcuL2R45xbIsximjWM6nM9b6F/kmZ3NILbyZfB4bPjdFKv0r5fS+KGMiHFbirW/VPlr59gm1QgApE+0LCe++H22gqg7PU9HfYiA35Wc14FGW08on1tjCXlpyjUIzZ+zVOTkBTYooLFop8FSy2Fl8Nt4/GoEDYxc0+BEV5RyJ/Q2QoPzGYQ2yTg7hgUlsJGPzJJ8AE+rc2rt2BAHEADev/ZfoddE+V1J6s1anPpIFUs8tHXiALlW3oWrwdBvaysJLI7J64a577Vfk0uOGNF5Mu5eKGB3B+xxrJJdW+nh2T2K9eA9jWLr3CF7Zwc7BqFqxWocz9pya5XlArpq3xxn5LARuo5AGk0/dFEzOSiOpxgD5o3Uc24IXn91JXuuQjx7f6iBz6gRZyRMZUl6q03Ow8tcrcSe0I4d91dILO6DNZ3kpNyKNb4triRQ+HvUEbSOnVmAU8hLJwR3TsM7AbQ4WGIkb1JLD9stcPPz1Y5f3OWXulnLvcZL7e5QSZFebWx5NCxGzWhzb3XfPDSmH52Iymz46LHrK3Ro3JJRB1a7EnlQAog1gqhKC4yAm7Of3AvtzEJMx7IqT0OwgceSOyfITwWmd/5+pnVOgROlj2ZGxKS0lxGGdIrbb2Ch+jWtGYjLXGr0Qr4jG1y/Sy8gXcAWgcM=
  distributions: sdist bdist_wheel
  skip_existing: true
notifications:
  email:
    on_success: never
    on_failure: always
